/* Generated By:JavaCC: Do not edit this line. SPARQLParserConstants.java */
package otservices.translator.language.sparql.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPARQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int UPDATE = 6;
  /** RegularExpression Id. */
  int WHERE = 7;
  /** RegularExpression Id. */
  int FILTER = 8;
  /** RegularExpression Id. */
  int REGEX = 9;
  /** RegularExpression Id. */
  int BOOL = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int VAR1 = 12;
  /** RegularExpression Id. */
  int VAR2 = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int FLOAT = 15;
  /** RegularExpression Id. */
  int INTP = 16;
  /** RegularExpression Id. */
  int INTN = 17;
  /** RegularExpression Id. */
  int FLOATP = 18;
  /** RegularExpression Id. */
  int FLOATN = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int PN_CHARS_U = 21;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"SELECT\"",
    "\"UPDATE\"",
    "\"WHERE\"",
    "\"FILTER\"",
    "\"REGEX\"",
    "<BOOL>",
    "<VAR>",
    "<VAR1>",
    "<VAR2>",
    "<INT>",
    "<FLOAT>",
    "<INTP>",
    "<INTN>",
    "<FLOATP>",
    "<FLOATN>",
    "<STRING>",
    "<PN_CHARS_U>",
    "<PN_CHARS_BASE>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"||\"",
    "\"&&\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\",\"",
  };

}
